on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: rust
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          persist-credentials: false

      - name: Configure Git authentication
        run: |
          git config --global url."https://${{ secrets.MY_RELEASE_PLEASE_TOKEN }}@github.com/".insteadOf "https://github.com/"
